openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:54851
  description: Generated server url
paths:
  /api/orders/{id}:
    get:
      tags:
      - order-endpoint
      operationId: getOrderById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDto"
    delete:
      tags:
      - order-endpoint
      operationId: cancelOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDto"
    patch:
      tags:
      - order-endpoint
      operationId: amendOrder
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AmendOrderRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDto"
  /api/trades:
    get:
      tags:
      - trade-endpoint
      operationId: getAllTrades
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TradeDto"
  /api/trades/{id}:
    get:
      tags:
      - trade-endpoint
      operationId: getTradeById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TradeDto"
  /api/orders:
    get:
      tags:
      - order-endpoint
      operationId: getAllOrders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderDto"
  /api/market/analytics:
    get:
      tags:
      - market-analytics-endpoint
      operationId: getMarketAnalytics
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MarketAnalyticsDto"
components:
  schemas:
    AmendOrderRequest:
      type: object
      properties:
        price:
          type: number
        quantity:
          type: number
      required:
      - price
      - quantity
    OrderDto:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        side:
          type: string
          enum:
          - BUY
          - SELL
        price:
          type: number
        quantity:
          type: number
        remainingQuantity:
          type: number
        timestamp:
          type: string
          format: date-time
        isFilled:
          type: boolean
        status:
          type: string
          enum:
          - OPEN
          - PARTIALLY_FILLED
          - PARTIALLY_FILLED_CANCELLED
          - CANCELLED
          - FILLED
      required:
      - id
      - isFilled
      - price
      - quantity
      - remainingQuantity
      - side
      - status
      - timestamp
      - userId
    TradeDto:
      type: object
      properties:
        id:
          type: string
        buyerId:
          type: string
        sellerId:
          type: string
        price:
          type: number
        quantity:
          type: number
        timestamp:
          type: string
          format: date-time
      required:
      - buyerId
      - id
      - price
      - quantity
      - sellerId
      - timestamp
    MarketAnalyticsDto:
      type: object
      properties:
        volume:
          type: number
        high:
          type: number
        low:
          type: number
        lastPrice:
          type: number
        bestBid:
          type: number
        bestAsk:
          type: number
      required:
      - volume
